export const API_ROOT = "http://localhost:8017";

export const provinces = [
  { name: "An Giang", value: 1 },
  { name: "Bà Rịa - Vũng Tàu", value: 2 },
  { name: "Bắc Giang", value: 3 },
  { name: "Bắc Kạn", value: 4 },
  { name: "Bạc Liêu", value: 5 },
  { name: "Bắc Ninh", value: 6 },
  { name: "Bến Tre", value: 7 },
  { name: "Bình Định", value: 8 },
  { name: "Bình Dương", value: 9 },
  { name: "Bình Phước", value: 10 },
  { name: "Bình Thuận", value: 11 },
  { name: "Cà Mau", value: 12 },
  { name: "Cần Thơ", value: 13 },
  { name: "Cao Bằng", value: 14 },
  { name: "Đà Nẵng", value: 15 },
  { name: "Đắk Lắk", value: 16 },
  { name: "Đắk Nông", value: 17 },
  { name: "Điện Biên", value: 18 },
  { name: "Đồng Nai", value: 19 },
  { name: "Đồng Tháp", value: 20 },
  { name: "Gia Lai", value: 21 },
  { name: "Hà Giang", value: 22 },
  { name: "Hà Nam", value: 23 },
  { name: "Hà Nội", value: 24 },
  { name: "Hà Tĩnh", value: 25 },
  { name: "Hải Dương", value: 26 },
  { name: "Hải Phòng", value: 27 },
  { name: "Hậu Giang", value: 28 },
  { name: "Hòa Bình", value: 29 },
  { name: "Hưng Yên", value: 30 },
  { name: "Khánh Hòa", value: 31 },
  { name: "Kiên Giang", value: 32 },
  { name: "Kon Tum", value: 33 },
  { name: "Lai Châu", value: 34 },
  { name: "Lâm Đồng", value: 35 },
  { name: "Lạng Sơn", value: 36 },
  { name: "Lào Cai", value: 37 },
  { name: "Long An", value: 38 },
  { name: "Nam Định", value: 39 },
  { name: "Nghệ An", value: 40 },
  { name: "Ninh Bình", value: 41 },
  { name: "Ninh Thuận", value: 42 },
  { name: "Phú Thọ", value: 43 },
  { name: "Phú Yên", value: 44 },
  { name: "Quảng Bình", value: 45 },
  { name: "Quảng Nam", value: 46 },
  { name: "Quảng Ngãi", value: 47 },
  { name: "Quảng Ninh", value: 48 },
  { name: "Quảng Trị", value: 49 },
  { name: "Sóc Trăng", value: 50 },
  { name: "Sơn La", value: 51 },
  { name: "Tây Ninh", value: 52 },
  { name: "Thái Bình", value: 53 },
  { name: "Thái Nguyên", value: 54 },
  { name: "Thanh Hóa", value: 55 },
  { name: "Thừa Thiên Huế", value: 56 },
  { name: "Tiền Giang", value: 57 },
  { name: "TP Hồ Chí Minh", value: 58 },
  { name: "Trà Vinh", value: 59 },
  { name: "Tuyên Quang", value: 60 },
  { name: "Vĩnh Long", value: 61 },
  { name: "Vĩnh Phúc", value: 62 },
  { name: "Yên Bái", value: 63 },
];
